name: unicode_scripts_blocks
description: A tool for checking if a code unit belongs to a Unicode Script or Block.
version: 0.4.0
homepage: https://github.com/suragch/unicode_scripts_blocks
author: Suragch <studymongolian@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
